version: '3.8'
services:
  backend:
    tty: true
    stdin_open: true
    build: 
      context: Electricity-app-Backend
      dockerfile: Dockerfile
  frontend:
    tty: true
    stdin_open: true
    build: 
      context: Electricity-app-frontend
      dockerfile: Dockerfile

  db:
    tty: true
    stdin_open: true
    build:
      context:  Electricity-app-backend
      dockerfile: db.Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  apis:
  frontend:
  db: