version: '3'
services:
  postgres:
    image: my-postgres
    container_name: postgres
    restart: always
    build:
      dockerfile: Dockerfile
      context: postgres
    ports:
      - "5432:5432"
    environment:
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432
        POSTGRES_USER: melissa
        POSTGRES_PASSWORD: 123
        POSTGRES_DB: electric
   
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: elec-db


  electricity-app-frontend:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: Electricity-app-frontend
    volumes:
      - ./Electricity-app-frontend:/Elec-app

  electricity-app-backend:
    build:
      dockerfile: Dockerfile
      context: Electricity-app-backend
    volumes:
      - ./Electricity-app-backend:/Elec-app
   
  volumes:
   frontend:
   backend:
   db: