name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Client Build and push
      uses: docker/build-push-action@v2
      with:
          context: ./Electric-app-frontend
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/electric-app-frontend:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/client:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/client:buildcache,mode=max
    - name: nginx Build and push
      uses: docker/build-push-action@v2
      with:
          context: ./nginx
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nginx:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/nginx:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/nginx:buildcache,mode=max

    - name: server Build and push
      uses: docker/build-push-action@v2
      with:
          context: ./Electric-app-backend
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/electric-app-backend:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/server:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/server:buildcache,mode=max
